#%RAML 1.0
title: Jar Notes REST Services API using Data Types
version: v1
protocols: [ HTTPS ] 
baseUri: http://localhost:8081/{version}
mediaType: application/json

types:
  Notes:
    type: object
    properties: 
      noteId: string
      noteTitle: string
      noteContent: string
      tagId: string[] /*  */
  Folders:
    type: object
    properties:
      folderId: string
      name: string
      noteId: string[]
      notesCollection: notes[]  /* Se puede tener una coleccion de notas dentro de otra coleccion? (folders) Para no
       tener que estar haciendo gets por cada id de nota -folders/notesCollection/ */
  Tags:
    type: object
    properties:
      tagId: string
      name: string
 
/notes:  
  /{noteId}:
  /noteTitle/{noteTitle}:
  /tagId/{tagId}:

/folders:
  /{folderId}:
  /{noteId}: /* Como hago el get? Si en folders tengo un arreglo de ids  */

/tags:
  /{tagId}:

/notes:
  get:
    description: Method used to list all the notes.
  post: 
    description: Method used to add a new note.
  /{noteId}:
    get:
      description: Method used to retrieve a specific note according to its ID.
    put:
    patch:
      description: Method used to update a specific note according to its ID.
    delete:  
      description: Method used to delete a specific note according to its ID.
  /noteTitle/{noteTitle}:
    get:
      description: Method used to get all the notes that matched the title of the note being specified in the api

/folders:
  get:
    description: Method used to list all the folders.
  post: 
    description: Method used to add a new folder.
  /{folderId}:
     get:
      description: Method used to retrieve a specific folder according to its ID.
    put:
    patch:
      description: Method used to update a specific folder according to its ID.
    delete:  
      description: Method used to delete a specific folder according to its ID.
  /{noteId}:
      description: "COMPLETAR LUEGO!!!!".

/tags: 




/notes:
  get:
  description: List all notes matching query criteria, if provided; otherwise list all notes
    queryParameters:
      noteTitle?: string
      


